# Generated by Django 4.2.3 on 2023-07-24 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demoapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drinks",
            old_name="drink",
            new_name="drink_name",
        ),
    ]
