# Generated by Django 4.2.3 on 2023-07-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demoapp", "0003_menucategory_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="category_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_name",
                to="demoapp.menucategory",
            ),
        ),
    ]
