# Generated by Django 4.2.3 on 2023-07-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demoapp", "0004_alter_menu_category_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("reservation_time", models.DateField(auto_now=True)),
                ("comments", models.CharField(max_length=1000)),
            ],
        ),
    ]
